services:
  whisper-api:
    image: the80hz/whisper-api:gpu
    build:
      args:
        INSTALL_GPU: "true"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all
