services:
  whisper-api:
    image: the80hz/whisper-api:latest
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./model-cache:/root/.cache/huggingface
    ports:
      - "${PORT:-3373}:${PORT:-3373}"
    restart: unless-stopped
    environment:
      PORT: "${PORT:-3373}"
